#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 3bc705f1-9e96-46e9-b768-8a45dd6a378f
# Source File: E:\OneDrive\PSDEMO\Powershell Studio 临时文件\Hyper-V Manager.psf
#------------------------------------------------------------------------

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2015 v4.2.81
     Generated on:       2016/11/29 17:47
     Generated by:       hongbiao
     Organization:       HBPS
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2015
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-Hyper-V_Manager_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$MainForm = New-Object 'System.Windows.Forms.Form'
	$B_StopVM = New-Object 'System.Windows.Forms.Button'
	$B_SaveVM = New-Object 'System.Windows.Forms.Button'
	$B_StartVM = New-Object 'System.Windows.Forms.Button'
	$VMINFO = New-Object 'System.Windows.Forms.GroupBox'
	$combobox1 = New-Object 'System.Windows.Forms.ComboBox'
	$L_VMINFO = New-Object 'System.Windows.Forms.Label'
	$GB_VMLIST = New-Object 'System.Windows.Forms.GroupBox'
	$LB_VMLIST = New-Object 'System.Windows.Forms.ListBox'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$MainForm_Load={
		#TODO: Initialize Form Controls here
		$script:VMList = Get-VM
		$VMList | select -ExpandProperty Name | foreach{
			$LB_VMLIST.Items.Add($_)
		}
	}
	
	#region Control Helper Functions
	function Load-ComboBox 
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ComboBox.
	
		.DESCRIPTION
			Use this function to dynamically load items into the ComboBox control.
	
		.PARAMETER  ComboBox
			The ComboBox control you want to add items to.
	
		.PARAMETER  Items
			The object or objects you wish to load into the ComboBox's Items collection.
	
		.PARAMETER  DisplayMember
			Indicates the property to display for the items in this control.
		
		.PARAMETER  Append
			Adds the item(s) to the ComboBox without clearing the Items collection.
		
		.EXAMPLE
			Load-ComboBox $combobox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Load-ComboBox $combobox1 "Red" -Append
			Load-ComboBox $combobox1 "White" -Append
			Load-ComboBox $combobox1 "Blue" -Append
		
		.EXAMPLE
			Load-ComboBox $combobox1 (Get-Process) "ProcessName"
	#>
		Param (
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			[System.Windows.Forms.ComboBox]$ComboBox,
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			$Items,
		    [Parameter(Mandatory=$false)]
			[string]$DisplayMember,
			[switch]$Append
		)
		
		if(-not $Append)
		{
			$ComboBox.Items.Clear()	
		}
		
		if($Items -is [Object[]])
		{
			$ComboBox.Items.AddRange($Items)
		}
		elseif ($Items -is [Array])
		{
			$ComboBox.BeginUpdate()
			foreach($obj in $Items)
			{
				$ComboBox.Items.Add($obj)	
			}
			$ComboBox.EndUpdate()
		}
		else
		{
			$ComboBox.Items.Add($Items)	
		}
	
		$ComboBox.DisplayMember = $DisplayMember	
	}
	
	function Load-ListBox 
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ListBox or CheckedListBox.
	
		.DESCRIPTION
			Use this function to dynamically load items into the ListBox control.
	
		.PARAMETER  ListBox
			The ListBox control you want to add items to.
	
		.PARAMETER  Items
			The object or objects you wish to load into the ListBox's Items collection.
	
		.PARAMETER  DisplayMember
			Indicates the property to display for the items in this control.
		
		.PARAMETER  Append
			Adds the item(s) to the ListBox without clearing the Items collection.
		
		.EXAMPLE
			Load-ListBox $ListBox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Load-ListBox $listBox1 "Red" -Append
			Load-ListBox $listBox1 "White" -Append
			Load-ListBox $listBox1 "Blue" -Append
		
		.EXAMPLE
			Load-ListBox $listBox1 (Get-Process) "ProcessName"
	#>
		Param (
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			[System.Windows.Forms.ListBox]$ListBox,
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			$Items,
		    [Parameter(Mandatory=$false)]
			[string]$DisplayMember,
			[switch]$Append
		)
		
		if(-not $Append)
		{
			$listBox.Items.Clear()	
		}
		
		if($Items -is [System.Windows.Forms.ListBox+ObjectCollection])
		{
			$listBox.Items.AddRange($Items)
		}
		elseif ($Items -is [Array])
		{
			$listBox.BeginUpdate()
			foreach($obj in $Items)
			{
				$listBox.Items.Add($obj)
			}
			$listBox.EndUpdate()
		}
		else
		{
			$listBox.Items.Add($Items)	
		}
	
		$listBox.DisplayMember = $DisplayMember	
	}
	#endregion
	
	$LB_VMLIST_SelectedValueChanged={
		#TODO: Place custom script here
		$SelectedVM = Get-VM -Name $LB_VMLIST.SelectedItem
		[string]$Text = "VMName : " + $SelectedVM.Name.tostring() + "`n" + "VMID : " + $SelectedVM.VMID.tostring() + "`n" + "VMSTATE : " + $SelectedVM.state.tostring()
		$L_VMINFO.Text = $Text
	}
	
	$B_StartVM_Click={
		#TODO: Place custom script here
		Start-VM $LB_VMLIST.SelectedItem
	}
	
	$B_SaveVM_Click={
		#TODO: Place custom script here
		Save-vm $LB_VMLIST.SelectedItem
	}
	
	$B_StopVM_Click={
		#TODO: Place custom script here
		Stop-VM $LB_VMLIST.SelectedItem
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$MainForm.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$B_StopVM.remove_Click($B_StopVM_Click)
			$B_SaveVM.remove_Click($B_SaveVM_Click)
			$B_StartVM.remove_Click($B_StartVM_Click)
			$LB_VMLIST.remove_SelectedValueChanged($LB_VMLIST_SelectedValueChanged)
			$MainForm.remove_Load($MainForm_Load)
			$MainForm.remove_Load($Form_StateCorrection_Load)
			$MainForm.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$MainForm.SuspendLayout()
	$VMINFO.SuspendLayout()
	$GB_VMLIST.SuspendLayout()
	#
	# MainForm
	#
	$MainForm.Controls.Add($B_StopVM)
	$MainForm.Controls.Add($B_SaveVM)
	$MainForm.Controls.Add($B_StartVM)
	$MainForm.Controls.Add($VMINFO)
	$MainForm.Controls.Add($GB_VMLIST)
	$MainForm.ClientSize = '556, 274'
	$MainForm.Font = "Microsoft YaHei UI, 8.25pt"
	$MainForm.MaximumSize = '572, 313'
	$MainForm.MinimumSize = '572, 313'
	$MainForm.Name = "MainForm"
	$MainForm.Text = "Hyper-V Manager"
	$MainForm.add_Load($MainForm_Load)
	#
	# B_StopVM
	#
	$B_StopVM.Location = '469, 241'
	$B_StopVM.Name = "B_StopVM"
	$B_StopVM.Size = '75, 23'
	$B_StopVM.TabIndex = 5
	$B_StopVM.Text = "StopVM"
	$B_StopVM.UseVisualStyleBackColor = $True
	$B_StopVM.add_Click($B_StopVM_Click)
	#
	# B_SaveVM
	#
	$B_SaveVM.Location = '350, 241'
	$B_SaveVM.Name = "B_SaveVM"
	$B_SaveVM.Size = '75, 23'
	$B_SaveVM.TabIndex = 4
	$B_SaveVM.Text = "SaveVM"
	$B_SaveVM.UseVisualStyleBackColor = $True
	$B_SaveVM.add_Click($B_SaveVM_Click)
	#
	# B_StartVM
	#
	$B_StartVM.Location = '226, 241'
	$B_StartVM.Name = "B_StartVM"
	$B_StartVM.Size = '75, 23'
	$B_StartVM.TabIndex = 3
	$B_StartVM.Text = "StartVM"
	$B_StartVM.UseVisualStyleBackColor = $True
	$B_StartVM.add_Click($B_StartVM_Click)
	#
	# VMINFO
	#
	$VMINFO.Controls.Add($combobox1)
	$VMINFO.Controls.Add($L_VMINFO)
	$VMINFO.Location = '225, 13'
	$VMINFO.Name = "VMINFO"
	$VMINFO.Size = '319, 222'
	$VMINFO.TabIndex = 2
	$VMINFO.TabStop = $False
	$VMINFO.Text = "VMINFO"
	#
	# combobox1
	#
	$combobox1.FormattingEnabled = $True
	$combobox1.Location = '42, 19'
	$combobox1.Name = "combobox1"
	$combobox1.Size = '121, 24'
	$combobox1.TabIndex = 1
	#
	# L_VMINFO
	#
	$L_VMINFO.Location = '7, 21'
	$L_VMINFO.Name = "L_VMINFO"
	$L_VMINFO.Size = '306, 190'
	$L_VMINFO.TabIndex = 0
	#
	# GB_VMLIST
	#
	$GB_VMLIST.Controls.Add($LB_VMLIST)
	$GB_VMLIST.Location = '13, 13'
	$GB_VMLIST.Name = "GB_VMLIST"
	$GB_VMLIST.Size = '206, 252'
	$GB_VMLIST.TabIndex = 1
	$GB_VMLIST.TabStop = $False
	$GB_VMLIST.Text = "VMLIST"
	#
	# LB_VMLIST
	#
	$LB_VMLIST.FormattingEnabled = $True
	$LB_VMLIST.ItemHeight = 16
	$LB_VMLIST.Location = '15, 22'
	$LB_VMLIST.Name = "LB_VMLIST"
	$LB_VMLIST.Size = '176, 212'
	$LB_VMLIST.TabIndex = 0
	$LB_VMLIST.add_SelectedValueChanged($LB_VMLIST_SelectedValueChanged)
	$GB_VMLIST.ResumeLayout()
	$VMINFO.ResumeLayout()
	$MainForm.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $MainForm.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$MainForm.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$MainForm.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $MainForm.ShowDialog()

} #End Function

#Call the form
Call-Hyper-V_Manager_psf | Out-Null
